### ISSUE TITLE
Add collaborators to this repo

### ISSUE THREAD

**Issue by cody-carlson** [bootcamp12345/caption-this-ftv#1]
## Comment below to be added as a collaborator

We will all be using this repository today. Even though it's public right now, you will not be able to make changes until you're given the correct permissions. We've automated this process via the GitHub API. Once you comment, we will add you as a collaborator.

You'll start to receive a lot of emails. (❗) You can slow these down immediately by clicking the **Unwatch** button at the top of the page and selecting either the **Participating and @mentions** or **Ignore** option.

**Comment by crawfordpw** [comment]
Hello!

**Comment by JamesCVober** [comment]
Hello

**Comment by JordanKoppelberger** [comment]
I have added a comment.

**Comment by HazyMyst** [comment]
Wazup?

**Comment by matt-keithley** [comment]
Hello

**Comment by LawKiz** [comment]
Reached this link

**Comment by Gamez97** [comment]
Hola!

**Comment by krakesKeithley** [comment]
Hi!

**Comment by jonaltenburger** [comment]
Leaving a comment

**Comment by ArvoDart** [comment]
Hi

**Comment by rossklonowski** [comment]
helloooo

**Comment by jgleonislas** [comment]
hello

**Comment by jesseulibarri** [comment]
Hey hey

**Comment by estarkey7** [comment]
Yup
